# e2e-tests for Metacatalog
name: e2e Test

on: ['push']

jobs:
  test:
    runs-on: ubuntu-18.04
    
    # create the postgis service - the version is hardcoded atm
    services:
      postgis:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - name: Chechout Repository
      uses: actions/checkout@v2
    
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # install metacatalog and test dependencies
    # e2e-tests rely on pytest and pytest-depends so far 
    - name: Install dependencies
      run: | 
        pip install -r requirements.txt
        python setup.py develop
        pip install pytest pytest-depends pytest-cov
      
    # activate the IO extension
    - name: Activate builtin IOExtension
      run: python -c "from metacatalog import ext; ext.activate_extension('io', 'metacatalog.ext.io', 'IOExtension')"

    # run the actual tests
    # they need the arbitrary port number which is mapped to 5432
    # in the VM host 
    # this has a lot of side-effects, as e2e is run against an 
    # actual database 
    - name: e2e Tests
      run: pytest --cov-config=.coveragerc --cov=./ --cov-report=xml
      env:
        POSTGRES_PORT: ${{ job.services.postgis.ports[5432] }}  
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: e2e
        env_vars: OS,PYTHON
