name: Documentation

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9
      
      - name: Install dependencies
        run: | 
          sudo apt install pandoc
          pip install wheel
          
      - name: Install package
        run: pip install -e .

      - name: Activate Extensions, install additional dependencies
        run: |
          pip install metacatalog-corr metacatalog-search
          pip install jinja2 lxml
      
      - name: Build Sphinx
        run: |
          pip install "sphinx<6" pandoc pydata_sphinx_theme nbsphinx sphinx-gallery
          cd docs
          make html
          cd build/html
          touch .nojekyll
      
      - name: Deploy
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs/build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
