name: Documentation

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      
      - name: Install dependencies
        run: | 
          sudo apt install pandoc
          pip install wheel
          
      - name: Install package
        run: python setup.py develop

      - name: Activate Extensions
        run: |
          pip install metacatalog-corr metacatalog-search
          python -c "from metacatalog import ext; ext.activate_extension('io', 'metacatalog.ext.io', 'IOExtension')"
          python -c "from metacatalog import ext; ext.activate_extension('search', 'metacatalog_search.extension', 'SearchExtension')"
          python -c "from metacatalog import ext; ext.activate_extension('corr', 'metacatalog_corr.extension', 'CorrExtension')"

      
      - name: Build Sphinx
        run: |
          pip install sphinx pandoc pydata_sphinx_theme nbsphinx sphinx-gallery
          cd docs
          make html
          cd build/html
          touch .nojekyll
      
      -  name: Deploy
         if: success()
         uses: crazy-max/ghaction-github-pages@v1
         with:
           target_branch: gh-pages
           build_dir: docs/build/html
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




