name: Documentation

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Use Python 3.6
        uses: actions/setup-python@v1
        with: 
          python-version: 3.6
      
      - name: Install
        run: python setup.py develop
      
      - name: Build Sphinx
        run: |
          pip install sphinx pandoc
          cd docs
          make html
          cd _build/html
          touch .nojekyll
      
      -  name: Deploy
         if: success()
         uses: crazy-max/ghaction-github-pages@v1
         with:
           taget_branch: gh-pages
           build_dir: docs/_build/html
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




