name: Documentation

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      
      - name: Install dependencies
        run: | 
          sudo apt install pandoc
          pip install wheel
          
      - name: Install package
        run: python setup.py develop
      
      - name: Build Sphinx
        run: |
          pip install sphinx pandoc pydata_sphinx_theme nbsphinx sphinx-gallery
          cd docs
          make html
          cd build/html
          touch .nojekyll
      
      -  name: Deploy
         if: success()
         uses: crazy-max/ghaction-github-pages@v1
         with:
           taget_branch: gh-pages
           build_dir: docs/build/html
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




