name: Documentation

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install Postgres
        uses: Harmon758/postgresql-action@v1.0.0
      -
        name: Install Requirements
        run: | 
          pip install psycopg2-binary
          pip install -r requirements.txt
          pip install .   
      -
        name: Build Sphinx
        run: | 
            cd docs
            make html
            cd ..
      -
         name: Deploy
         if: success()
         uses: crazy-max/ghaction-github-pages@v1
         with:
           taget_branch: gh-pages
           build_dir: docs/_build/html
         env:
           GITHUB_PAT: ${{ secrets.GITHUB_PAT }}}




